### ISSUE TITLE
The graphs and gallery pages are empty

### ISSUE THREAD

**Issue by TomAmpiath** [jhanaveenk/DesktopApp_Assigment#1]
Please see the attached images
![Screenshot 2023-02-25 122027](https://user-images.githubusercontent.com/74437170/221343389-0c55ba32-b455-460c-b145-977e8b2d451b.png)
![Screenshot 2023-02-25 122045](https://user-images.githubusercontent.com/74437170/221343391-fa10250d-381d-4760-b361-12b14c389d81.png)

**Comment by jhanaveenk** [comment]
yeah, I tried to fix it by connecting to databse. but unable to. can you help me on how to do it propely?

**Comment by jhanaveenk** [comment]
graphs and image are showing now.

**Comment by jhanaveenk** [comment]
graphs and image are showing up now, had minor error in loop while pushing
![Screenshot (5)](https://user-images.githubusercontent.com/71990959/221371255-ff49089d-4cf3-4856-9cf0-8ca1d243f21e.png)
![Screenshot (6)](https://user-images.githubusercontent.com/71990959/221371258-19434fc8-2865-483a-9481-4d8c59f036b9.png)
![Screenshot (7)](https://user-images.githubusercontent.com/71990959/221371259-1285b5b2-b834-4ff0-b29e-80611ec5da99.png)
![Screenshot (8)](https://user-images.githubusercontent.com/71990959/221371261-51c6fa2d-646f-420e-a3f1-be2a1d2fa62c.png)
![Screenshot (9)](https://user-images.githubusercontent.com/71990959/221371262-1db873ba-d40a-418d-827d-2093d22bc283.png)
![Screenshot (10)](https://user-images.githubusercontent.com/71990959/221371263-31f796df-c989-4bf9-817f-b89c269a781a.png)
![Screenshot (11)](https://user-images.githubusercontent.com/71990959/221371264-ffd81f20-97a1-414e-b9c8-08cc97489843.png)
![Screenshot (12)](https://user-images.githubusercontent.com/71990959/221371265-bd50a6e9-ad24-4dba-acd7-e3eff8fa70ae.png)
